export * from "./schema"
export * from "./types"
export { calculateNicaraguaSalaryNet } from "./ni/calculate"
export { calculateElSalvadorSalaryNet } from "./sv/calculate"
export { calculateHondurasSalaryNet } from "./hn/calculate"
export { calculateGuatemalaSalaryNet } from "./gt/calculate"
export { calculateCostaRicaSalaryNet } from "./cr/calculate"
export { calculatePanamaSalaryNet } from "./pa/calculate"
export { calculateMexicoSalaryNet } from "./mx/calculate"
export { calculateColombiaSalaryNet } from "./co/calculate"
export { calculatePeruSalaryNet } from "./pe/calculate"
export { calculateChileSalaryNet } from "./cl/calculate"
export { calculateArgentinaSalaryNet } from "./ar/calculate"
